project_id = "aoxdosjkwqyuvccuwhzc"

[functions.admin-get-users]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.sprint-summary]
verify_jwt = false
