WITH catalog(object_name) AS (
  VALUES
  ('admin_allocation_methods'),('admin_approver_management'),('admin_attendance_holiday_management'),
  ('admin_attendance_leave_approvals'),('admin_attendance_leave_balances'),('admin_attendance_live_monitoring'),
  ('admin_attendance_mgmt'),('admin_attendance_policy_config'),('admin_attendance_regularization_approvals'),
  ('admin_attendance_working_days'),('admin_badges_management'),('admin_bank_information'),
  ('admin_branding_requests'),('admin_checkin_monitoring'),('admin_company_details'),
  ('admin_company_profile'),('admin_competition_insights'),('admin_credit_limits'),
  ('admin_credit_mgmt'),('admin_credit_scoring_config'),('admin_dashboard'),
  ('admin_dashboard_overview'),('admin_distributor_assignment'),('admin_distributor_portal'),
  ('admin_expense_analytics'),('admin_expense_approvals'),('admin_expense_claims_list'),
  ('admin_expense_mgmt'),('admin_expense_policy_config'),('admin_feature_flags'),
  ('admin_feature_mgmt'),('admin_feature_toggle'),('admin_feedback_list'),
  ('admin_feedback_mgmt'),('admin_gamification'),('admin_gamification_config'),
  ('admin_gps_journey_playback'),('admin_gps_live_location'),('admin_gps_team_tracking'),
  ('admin_gps_track_mgmt'),('admin_header_branding'),('admin_hierarchy_target_setup'),
  ('admin_hierarchy_targets'),('admin_invoice_create'),('admin_invoice_list'),
  ('admin_invoice_mgmt'),('admin_invoice_templates'),('admin_loyalty_points'),
  ('admin_loyalty_programs'),('admin_loyalty_redemptions'),('admin_operations'),
  ('admin_operations_dashboard'),('admin_order_monitoring'),('admin_panel'),
  ('admin_permanent_deletion_logs'),('admin_portal_claims'),('admin_portal_ideas'),
  ('admin_portal_inventory'),('admin_portal_orders'),('admin_portal_support'),
  ('admin_portal_users'),('admin_price_book'),('admin_price_book_assignment'),
  ('admin_price_book_create'),('admin_price_book_delete'),('admin_price_book_edit'),
  ('admin_price_book_list'),('admin_product_bulk_import'),('admin_product_categories'),
  ('admin_product_create'),('admin_product_delete'),('admin_product_edit'),
  ('admin_product_list'),('admin_product_mgmt'),('admin_profile_permissions'),
  ('admin_recycle_bin'),('admin_recycle_bin_settings'),('admin_redemption_management'),
  ('admin_region_management'),('admin_restore_deleted_items'),('admin_retail_mgmt'),
  ('admin_retailer_list'),('admin_retailer_loyalty'),('admin_retailer_photo_update'),
  ('admin_retailer_territory_assignment'),('admin_retailer_verification'),('admin_rewards_management'),
  ('admin_scheme_applicability'),('admin_scheme_create'),('admin_scheme_delete'),
  ('admin_scheme_edit'),('admin_scheme_list'),('admin_scheme_master'),
  ('admin_scheme_policy_config'),('admin_security_access'),('admin_security_profiles'),
  ('admin_security_roles_display'),('admin_stock_monitoring'),('admin_target_cascade'),
  ('admin_target_setting'),('admin_target_tracking'),('admin_target_vs_actual'),
  ('admin_territories_distributors'),('admin_territory_management'),('admin_user_activate_deactivate'),
  ('admin_user_create'),('admin_user_delete'),('admin_user_edit'),
  ('admin_user_hierarchy'),('admin_user_list'),('admin_user_reset_password'),
  ('admin_user_specific_permissions'),('admin_van_create'),('admin_van_driver_assignment'),
  ('admin_van_edit'),('admin_van_list'),('admin_van_opening_grn_edits'),
  ('admin_van_sales'),('admin_van_stock_view'),('admin_vendor_approvals'),
  ('admin_vendor_create'),('admin_vendor_edit'),('admin_vendor_list'),
  ('admin_vendor_mgmt'),('all_retailers'),('analytics'),
  ('analytics_beat_details'),('analytics_business_summary'),('analytics_date_range_picker'),
  ('analytics_leaderboard'),('analytics_order_details'),('analytics_pending_payments'),
  ('analytics_performance_calendar'),('analytics_product_breakdown'),('analytics_retailer_details'),
  ('analytics_user_filter'),('attendance'),('attendance_check_in_out'),
  ('attendance_face_verification'),('attendance_holiday_list'),('attendance_journey_map'),
  ('attendance_leave_applications'),('attendance_photo_capture'),('attendance_regularization_requests'),
  ('attendance_statistics'),('attendance_timeline_view'),('beat_analytics'),
  ('beat_create'),('beat_detail'),('beat_list'),('beat_retailer_assignment'),
  ('beat_schedule'),('beat_travel_allowance'),('check_schemes'),
  ('competency'),('competency_dashboard'),('competency_detail'),('competency_team'),
  ('competition_competitor_detail'),('competition_competitor_list'),('competition_master'),
  ('competition_news_articles'),('competition_regional_presence'),('competition_sales_team_size'),
  ('competition_sku_comparison'),('competition_swot_analysis'),('delivery_detail'),
  ('delivery_list'),('delivery_status_update'),('distributor_add'),
  ('distributor_coverage_area'),('distributor_detail'),('distributor_edit'),
  ('distributor_fleet_size'),('distributor_list'),('distributor_master'),
  ('distributor_partnership_status'),('distributor_retailer_mapping'),('expense_approval_status'),
  ('expense_beat_allowance'),('expense_claim_history'),('expense_claims'),
  ('expense_distance_calculation'),('gamification'),('gamification_badges'),
  ('gamification_leaderboard'),('gamification_redemption'),('gamification_rewards'),
  ('gps_distance_traveled'),('gps_journey_playback'),('gps_live_tracking'),
  ('gps_team_status'),('gps_time_analytics'),('gps_track'),('gps_visit_statistics'),
  ('institutional_accounts'),('institutional_collections'),('institutional_contacts'),
  ('institutional_dashboard'),('institutional_invoices'),('institutional_leads'),
  ('institutional_opportunities'),('institutional_order_commitments'),('institutional_price_books'),
  ('institutional_products'),('institutional_quotes'),('institutional_sales'),
  ('my_beats'),('my_deliveries'),('my_expenses'),('my_target'),('my_visit'),
  ('packing_list'),('packing_list_create'),('packing_list_manage'),('packing_list_view'),
  ('performance'),('performance_beat_breakdown'),('performance_leaderboard'),
  ('performance_overall'),('performance_period_comparison'),('performance_retailer_breakdown'),
  ('performance_territory_breakdown'),('performance_trend_analysis'),('primary_order_create'),
  ('primary_order_details'),('primary_order_dispatch_date'),('primary_order_inventory_sync'),
  ('primary_order_list'),('primary_order_status'),('primary_order_transporter_info'),
  ('primary_orders'),('recycle_bin'),('recycle_permanent_delete'),('recycle_restore'),
  ('recycle_view'),('retailer_add'),('retailer_analytics'),('retailer_beat_assignment'),
  ('retailer_bulk_import'),('retailer_category_filter'),('retailer_credit_score'),
  ('retailer_detail'),('retailer_list'),('retailer_location_map'),('retailer_order_history'),
  ('scheme_active_schemes'),('scheme_applicability'),('scheme_details'),
  ('scheme_tiered_offers'),('scheme_types'),('scheme_validity_tracking'),
  ('target_achievement_percentage'),('target_ai_recommendations'),('target_beat_performance'),
  ('target_overview'),('target_period_selection'),('target_retailer_performance'),
  ('target_shortfall_analysis'),('target_territory_performance'),('tax_component_manage'),
  ('tax_master'),('tax_master_create'),('tax_master_delete'),('tax_master_edit'),
  ('tax_master_list'),('tax_product_mapping'),('territories'),('territory_assignment'),
  ('territory_coverage_statistics'),('territory_detail'),('territory_list'),
  ('territory_region_management'),('user_management'),('user_mgmt_activate_deactivate'),
  ('user_mgmt_create'),('user_mgmt_delete'),('user_mgmt_edit'),('user_mgmt_hierarchy'),
  ('user_mgmt_list'),('user_mgmt_reset_password'),('visit_activity'),('visit_activity_log'),
  ('visit_activity_sync'),('visit_activity_view'),('visit_ai_recommendations'),
  ('visit_all_beat'),('visit_all_beat_retailers'),('visit_all_beat_select'),
  ('visit_all_beat_view'),('visit_auto_plan'),('visit_auto_plan_edit'),
  ('visit_auto_plan_generate'),('visit_auto_plan_view'),('visit_gps_track'),
  ('visit_gps_track_playback'),('visit_gps_track_view'),('visit_points_gamification'),
  ('visit_retailer_check_in'),('visit_retailer_create_visit'),('visit_retailer_list'),
  ('visit_retailer_no_order'),('visit_retailer_order_entry'),('visit_retailers'),
  ('visit_summary'),('visit_summary_export'),('visit_summary_insights'),
  ('visit_summary_view'),('visit_timeline'),('visit_timeline_details'),
  ('visit_timeline_view'),('visit_todays_progress'),('visit_todays_progress_view'),
  ('visit_van_stock'),('visit_van_stock_manage'),('visit_van_stock_view')
)
INSERT INTO public.profile_object_permissions
  (profile_id, object_name, permission_type, parent_module,
   can_read, can_create, can_edit, can_delete, can_view_all, can_modify_all)
SELECT sp.id, c.object_name, 'sub_feature', NULL,
       true, true, true, true, true, true
  FROM public.security_profiles sp
  CROSS JOIN catalog c
 WHERE sp.is_system = true
ON CONFLICT (profile_id, object_name, permission_type) DO UPDATE
  SET can_read       = true,
      can_create     = true,
      can_edit       = true,
      can_delete     = true,
      can_view_all   = true,
      can_modify_all = true;

DO $$
DECLARE v_missing INT;
BEGIN
  SELECT 3 - COUNT(*) INTO v_missing
    FROM public.profile_object_permissions
   WHERE profile_id = '98c1259e-0368-4e1a-a4e8-01e173cbfb10'
     AND object_name IN ('analytics_business_summary',
                         'analytics_order_details',
                         'analytics_product_breakdown')
     AND can_read;
  IF v_missing <> 0 THEN
    RAISE EXCEPTION 'Analytics tab keys still missing for System Administrator (missing=%)', v_missing;
  END IF;
END$$;