WITH catalog(object_name, permission_type, parent_module) AS (
  VALUES
  ('module_attendance','module',NULL),
  ('field_attendance_pct_this_month','field','attendance'),
  ('field_attendance_present_days','field','attendance'),
  ('field_attendance_absent_days','field','attendance'),
  ('field_attendance_working_hours','field','attendance'),
  ('field_attendance_market_hours','field','attendance'),
  ('field_attendance_first_checkin','field','attendance'),
  ('field_attendance_last_checkout','field','attendance'),
  ('field_attendance_location','field','attendance'),
  ('action_attendance_check_in','action','attendance'),
  ('action_attendance_check_out','action','attendance'),
  ('action_attendance_apply_leave','action','attendance'),
  ('action_attendance_regularize','action','attendance'),
  ('action_attendance_start_market_hours','action','attendance'),
  ('action_attendance_stop_market_hours','action','attendance'),
  ('action_attendance_face_verification','action','attendance'),
  ('action_attendance_photo_capture','action','attendance'),
  ('widget_attendance_my_attendance_tab','widget','attendance'),
  ('widget_attendance_my_team_tab','widget','attendance'),
  ('widget_attendance_records_table','widget','attendance'),
  ('widget_attendance_leave_tab','widget','attendance'),
  ('widget_attendance_holiday_tab','widget','attendance'),
  ('widget_attendance_journey_map','widget','attendance'),
  ('widget_attendance_timeline_view','widget','attendance'),
  ('widget_attendance_monthly_summary','widget','attendance'),
  ('module_my_visit','module',NULL),
  ('field_visit_date','field','my_visit'),
  ('field_visit_retailer_name','field','my_visit'),
  ('field_visit_beat_name','field','my_visit'),
  ('field_visit_checkin_time','field','my_visit'),
  ('field_visit_duration','field','my_visit'),
  ('field_visit_order_value','field','my_visit'),
  ('field_visit_status','field','my_visit'),
  ('field_visit_distributor','field','my_visit'),
  ('action_visit_auto_plan','action','my_visit'),
  ('action_visit_all_beat','action','my_visit'),
  ('action_visit_retailers','action','my_visit'),
  ('action_visit_summary','action','my_visit'),
  ('action_visit_timeline','action','my_visit'),
  ('action_visit_gps_track','action','my_visit'),
  ('action_visit_van_stock','action','my_visit'),
  ('action_visit_activity','action','my_visit'),
  ('widget_visit_todays_progress','widget','my_visit'),
  ('widget_visit_points_earned','widget','my_visit'),
  ('widget_visit_week_calendar','widget','my_visit'),
  ('widget_visit_retailer_card_list','widget','my_visit'),
  ('widget_visit_orders_dialog','widget','my_visit'),
  ('widget_visit_filters','widget','my_visit'),
  ('widget_visit_ai_recommendations','widget','my_visit'),
  ('widget_visit_sync_data_modal','widget','my_visit'),
  ('module_all_retailers','module',NULL),
  ('field_retailer_name','field','all_retailers'),
  ('field_retailer_address','field','all_retailers'),
  ('field_retailer_phone','field','all_retailers'),
  ('field_retailer_category','field','all_retailers'),
  ('field_retailer_priority','field','all_retailers'),
  ('field_retailer_beat_name','field','all_retailers'),
  ('field_retailer_last_visit_date','field','all_retailers'),
  ('field_retailer_credit_score','field','all_retailers'),
  ('field_retailer_pending_amount','field','all_retailers'),
  ('field_retailer_gst_number','field','all_retailers'),
  ('field_retailer_location_tag','field','all_retailers'),
  ('field_retailer_retail_type','field','all_retailers'),
  ('field_retailer_potential','field','all_retailers'),
  ('action_retailer_add','action','all_retailers'),
  ('action_retailer_edit','action','all_retailers'),
  ('action_retailer_delete','action','all_retailers'),
  ('action_retailer_bulk_import','action','all_retailers'),
  ('action_retailer_mass_edit_beats','action','all_retailers'),
  ('action_retailer_add_to_visit','action','all_retailers'),
  ('action_retailer_view_analytics','action','all_retailers'),
  ('action_retailer_export','action','all_retailers'),
  ('widget_retailer_list_table','widget','all_retailers'),
  ('widget_retailer_detail_modal','widget','all_retailers'),
  ('widget_retailer_analytics_panel','widget','all_retailers'),
  ('widget_retailer_credit_score_display','widget','all_retailers'),
  ('widget_retailer_pagination','widget','all_retailers'),
  ('widget_retailer_search_filter','widget','all_retailers'),
  ('module_my_beats','module',NULL),
  ('field_beat_name','field','my_beats'),
  ('field_beat_schedule','field','my_beats'),
  ('field_beat_retailer_count','field','my_beats'),
  ('field_beat_territory','field','my_beats'),
  ('field_beat_travel_allowance','field','my_beats'),
  ('action_beat_create','action','my_beats'),
  ('action_beat_edit','action','my_beats'),
  ('action_beat_delete','action','my_beats'),
  ('action_beat_assign_retailers','action','my_beats'),
  ('widget_beat_list','widget','my_beats'),
  ('widget_beat_detail','widget','my_beats'),
  ('widget_beat_analytics','widget','my_beats'),
  ('widget_beat_calendar','widget','my_beats'),
  ('module_my_target','module',NULL),
  ('field_target_value','field','my_target'),
  ('field_target_achievement_pct','field','my_target'),
  ('field_target_period','field','my_target'),
  ('field_target_shortfall','field','my_target'),
  ('action_target_view_details','action','my_target'),
  ('action_target_export','action','my_target'),
  ('action_target_compare_periods','action','my_target'),
  ('widget_target_overview','widget','my_target'),
  ('widget_target_territory_performance','widget','my_target'),
  ('widget_target_beat_performance','widget','my_target'),
  ('widget_target_retailer_performance','widget','my_target'),
  ('widget_target_ai_recommendations','widget','my_target'),
  ('widget_target_shortfall_analysis','widget','my_target'),
  ('module_analytics','module',NULL),
  ('field_analytics_revenue','field','analytics'),
  ('field_analytics_orders_count','field','analytics'),
  ('field_analytics_coverage_pct','field','analytics'),
  ('field_analytics_pending_payments','field','analytics'),
  ('action_analytics_export','action','analytics'),
  ('action_analytics_filter','action','analytics'),
  ('action_analytics_date_range','action','analytics'),
  ('action_analytics_user_filter','action','analytics'),
  ('widget_analytics_business_summary','widget','analytics'),
  ('widget_analytics_beat_details','widget','analytics'),
  ('widget_analytics_retailer_details','widget','analytics'),
  ('widget_analytics_order_details','widget','analytics'),
  ('widget_analytics_product_breakdown','widget','analytics'),
  ('widget_analytics_pending_payments','widget','analytics'),
  ('widget_analytics_performance_calendar','widget','analytics'),
  ('widget_analytics_leaderboard','widget','analytics'),
  ('module_gps_track','module',NULL),
  ('field_gps_location','field','gps_track'),
  ('field_gps_distance_traveled','field','gps_track'),
  ('field_gps_duration','field','gps_track'),
  ('field_gps_visit_count','field','gps_track'),
  ('action_gps_start_tracking','action','gps_track'),
  ('action_gps_journey_playback','action','gps_track'),
  ('action_gps_export','action','gps_track'),
  ('widget_gps_live_map','widget','gps_track'),
  ('widget_gps_timeline','widget','gps_track'),
  ('widget_gps_visit_statistics','widget','gps_track'),
  ('widget_gps_time_analytics','widget','gps_track'),
  ('widget_gps_team_status','widget','gps_track'),
  ('module_performance','module',NULL),
  ('field_performance_overall_score','field','performance'),
  ('field_performance_rank','field','performance'),
  ('field_performance_trend','field','performance'),
  ('action_performance_export','action','performance'),
  ('action_performance_compare_periods','action','performance'),
  ('widget_performance_overall','widget','performance'),
  ('widget_performance_territory_breakdown','widget','performance'),
  ('widget_performance_beat_breakdown','widget','performance'),
  ('widget_performance_retailer_breakdown','widget','performance'),
  ('widget_performance_period_comparison','widget','performance'),
  ('widget_performance_trend_analysis','widget','performance'),
  ('widget_performance_leaderboard','widget','performance'),
  ('module_primary_orders','module',NULL),
  ('field_order_number','field','primary_orders'),
  ('field_order_amount','field','primary_orders'),
  ('field_order_status','field','primary_orders'),
  ('field_order_date','field','primary_orders'),
  ('field_order_transporter_info','field','primary_orders'),
  ('field_order_dispatch_date','field','primary_orders'),
  ('action_order_create','action','primary_orders'),
  ('action_order_view_details','action','primary_orders'),
  ('action_order_inventory_sync','action','primary_orders'),
  ('widget_order_list','widget','primary_orders'),
  ('widget_order_status_board','widget','primary_orders'),
  ('widget_order_details','widget','primary_orders'),
  ('module_my_expenses','module',NULL),
  ('field_expense_amount','field','my_expenses'),
  ('field_expense_category','field','my_expenses'),
  ('field_expense_date','field','my_expenses'),
  ('field_expense_status','field','my_expenses'),
  ('field_expense_distance','field','my_expenses'),
  ('action_expense_submit_claim','action','my_expenses'),
  ('action_expense_edit_claim','action','my_expenses'),
  ('action_expense_export','action','my_expenses'),
  ('widget_expense_beat_allowance','widget','my_expenses'),
  ('widget_expense_claims','widget','my_expenses'),
  ('widget_expense_claim_history','widget','my_expenses'),
  ('widget_expense_approval_status','widget','my_expenses'),
  ('module_gamification','module',NULL),
  ('field_gamification_points','field','gamification'),
  ('field_gamification_rank','field','gamification'),
  ('field_gamification_badges','field','gamification'),
  ('action_gamification_redeem','action','gamification'),
  ('action_gamification_view_details','action','gamification'),
  ('widget_gamification_leaderboard','widget','gamification'),
  ('widget_gamification_badges','widget','gamification'),
  ('widget_gamification_rewards','widget','gamification'),
  ('widget_gamification_redemption','widget','gamification'),
  ('module_distributor_master','module',NULL),
  ('field_dist_name','field','distributor_master'),
  ('field_dist_territory','field','distributor_master'),
  ('field_dist_contact','field','distributor_master'),
  ('field_dist_credit_limit','field','distributor_master'),
  ('field_dist_outstanding','field','distributor_master'),
  ('action_dist_add','action','distributor_master'),
  ('action_dist_edit','action','distributor_master'),
  ('action_dist_view_ledger','action','distributor_master'),
  ('widget_dist_list','widget','distributor_master'),
  ('widget_dist_detail','widget','distributor_master'),
  ('widget_dist_ledger','widget','distributor_master'),
  ('module_territories','module',NULL),
  ('field_territory_name','field','territories'),
  ('field_territory_region','field','territories'),
  ('field_territory_assigned_user','field','territories'),
  ('field_territory_pincode_ranges','field','territories'),
  ('action_territory_create','action','territories'),
  ('action_territory_edit','action','territories'),
  ('action_territory_assign','action','territories'),
  ('widget_territory_list','widget','territories'),
  ('widget_territory_map','widget','territories'),
  ('widget_territory_performance','widget','territories'),
  ('module_competition_master','module',NULL),
  ('field_comp_competitor_name','field','competition_master'),
  ('field_comp_product','field','competition_master'),
  ('field_comp_price','field','competition_master'),
  ('field_comp_market_share','field','competition_master'),
  ('action_comp_add_insight','action','competition_master'),
  ('action_comp_edit_insight','action','competition_master'),
  ('action_comp_export','action','competition_master'),
  ('widget_comp_insights_list','widget','competition_master'),
  ('widget_comp_comparison_chart','widget','competition_master'),
  ('module_check_schemes','module',NULL),
  ('field_scheme_name','field','check_schemes'),
  ('field_scheme_type','field','check_schemes'),
  ('field_scheme_validity','field','check_schemes'),
  ('field_scheme_discount','field','check_schemes'),
  ('action_scheme_view_details','action','check_schemes'),
  ('action_scheme_apply','action','check_schemes'),
  ('widget_scheme_list','widget','check_schemes'),
  ('widget_scheme_detail','widget','check_schemes'),
  ('widget_scheme_eligibility','widget','check_schemes'),
  ('module_packing_list','module',NULL),
  ('field_packing_list_number','field','packing_list'),
  ('field_packing_delivery_date','field','packing_list'),
  ('field_packing_items','field','packing_list'),
  ('field_packing_status','field','packing_list'),
  ('action_packing_create','action','packing_list'),
  ('action_packing_edit','action','packing_list'),
  ('action_packing_mark_delivered','action','packing_list'),
  ('widget_packing_list','widget','packing_list'),
  ('widget_packing_detail','widget','packing_list'),
  ('module_my_deliveries','module',NULL),
  ('field_delivery_order_number','field','my_deliveries'),
  ('field_delivery_retailer','field','my_deliveries'),
  ('field_delivery_date','field','my_deliveries'),
  ('field_delivery_status','field','my_deliveries'),
  ('field_delivery_amount','field','my_deliveries'),
  ('action_delivery_mark_delivered','action','my_deliveries'),
  ('action_delivery_collect_payment','action','my_deliveries'),
  ('action_delivery_view_details','action','my_deliveries'),
  ('widget_delivery_list','widget','my_deliveries'),
  ('widget_delivery_detail','widget','my_deliveries'),
  ('widget_delivery_payment_collection','widget','my_deliveries'),
  ('module_recycle_bin','module',NULL),
  ('field_recycle_item_name','field','recycle_bin'),
  ('field_recycle_deleted_at','field','recycle_bin'),
  ('field_recycle_deleted_by','field','recycle_bin'),
  ('field_recycle_item_type','field','recycle_bin'),
  ('action_recycle_restore','action','recycle_bin'),
  ('action_recycle_permanent_delete','action','recycle_bin'),
  ('widget_recycle_list','widget','recycle_bin'),
  ('widget_recycle_filter','widget','recycle_bin'),
  ('module_competency','module',NULL),
  ('field_competency_name','field','competency'),
  ('field_competency_score','field','competency'),
  ('field_competency_category','field','competency'),
  ('field_competency_level','field','competency'),
  ('action_competency_take_quiz','action','competency'),
  ('action_competency_view_content','action','competency'),
  ('action_competency_export','action','competency'),
  ('widget_competency_overview','widget','competency'),
  ('widget_competency_quiz','widget','competency'),
  ('widget_competency_content','widget','competency'),
  ('widget_competency_badges','widget','competency'),
  ('module_homepage','module',NULL),
  ('field_homepage_greeting','field','homepage'),
  ('field_homepage_attendance_summary','field','homepage'),
  ('field_homepage_sales_summary','field','homepage'),
  ('field_homepage_notifications','field','homepage'),
  ('field_homepage_quick_stats','field','homepage'),
  ('field_homepage_beat_plan','field','homepage'),
  ('field_homepage_target_progress','field','homepage'),
  ('action_homepage_check_in','action','homepage'),
  ('action_homepage_check_out','action','homepage'),
  ('action_homepage_end_day','action','homepage'),
  ('action_homepage_refresh','action','homepage'),
  ('action_homepage_quick_add','action','homepage'),
  ('action_homepage_quick_nav','action','homepage'),
  ('widget_homepage_attendance','widget','homepage'),
  ('widget_homepage_sales_summary','widget','homepage'),
  ('widget_homepage_visit_plan','widget','homepage'),
  ('widget_homepage_announcements','widget','homepage'),
  ('widget_homepage_quick_links','widget','homepage'),
  ('widget_homepage_performance','widget','homepage'),
  ('widget_homepage_target_achievement','widget','homepage'),
  ('widget_homepage_day_status','widget','homepage'),
  ('module_admin_control','module',NULL),
  ('admin_panel','module',NULL),
  ('admin_dashboard','module',NULL),
  ('admin_dashboard_overview','module',NULL),
  ('admin_user_list','module',NULL),
  ('admin_user_create','module',NULL),
  ('admin_user_edit','module',NULL),
  ('admin_user_delete','module',NULL),
  ('admin_user_activate_deactivate','module',NULL),
  ('admin_user_reset_password','module',NULL),
  ('admin_user_hierarchy','module',NULL),
  ('admin_approver_management','module',NULL),
  ('admin_security_roles_display','module',NULL),
  ('admin_price_book','module',NULL),
  ('admin_price_book_list','module',NULL),
  ('admin_price_book_create','module',NULL),
  ('admin_price_book_edit','module',NULL),
  ('admin_price_book_delete','module',NULL),
  ('admin_price_book_assignment','module',NULL),
  ('admin_attendance_mgmt','module',NULL),
  ('admin_attendance_live_monitoring','module',NULL),
  ('admin_attendance_leave_approvals','module',NULL),
  ('admin_attendance_regularization_approvals','module',NULL),
  ('admin_attendance_holiday_management','module',NULL),
  ('admin_attendance_leave_balances','module',NULL),
  ('admin_attendance_policy_config','module',NULL),
  ('admin_attendance_working_days','module',NULL),
  ('admin_product_mgmt','module',NULL),
  ('admin_product_list','module',NULL),
  ('admin_product_create','module',NULL),
  ('admin_product_edit','module',NULL),
  ('admin_product_delete','module',NULL),
  ('admin_product_categories','module',NULL),
  ('admin_product_bulk_import','module',NULL),
  ('admin_scheme_master','module',NULL),
  ('admin_scheme_list','module',NULL),
  ('admin_scheme_create','module',NULL),
  ('admin_scheme_edit','module',NULL),
  ('admin_scheme_delete','module',NULL),
  ('admin_scheme_applicability','module',NULL),
  ('admin_scheme_policy_config','module',NULL),
  ('admin_vendor_mgmt','module',NULL),
  ('admin_vendor_list','module',NULL),
  ('admin_vendor_create','module',NULL),
  ('admin_vendor_edit','module',NULL),
  ('admin_vendor_approvals','module',NULL),
  ('admin_territories_distributors','module',NULL),
  ('admin_territory_management','module',NULL),
  ('admin_distributor_assignment','module',NULL),
  ('admin_region_management','module',NULL),
  ('admin_expense_mgmt','module',NULL),
  ('admin_expense_claims_list','module',NULL),
  ('admin_expense_approvals','module',NULL),
  ('admin_expense_analytics','module',NULL),
  ('admin_expense_policy_config','module',NULL),
  ('admin_feedback_mgmt','module',NULL),
  ('admin_feedback_list','module',NULL),
  ('admin_competition_insights','module',NULL),
  ('admin_branding_requests','module',NULL),
  ('admin_operations','module',NULL),
  ('admin_operations_dashboard','module',NULL),
  ('admin_checkin_monitoring','module',NULL),
  ('admin_order_monitoring','module',NULL),
  ('admin_stock_monitoring','module',NULL),
  ('admin_gps_track_mgmt','module',NULL),
  ('admin_gps_live_location','module',NULL),
  ('admin_gps_journey_playback','module',NULL),
  ('admin_gps_team_tracking','module',NULL),
  ('admin_retail_mgmt','module',NULL),
  ('admin_retailer_list','module',NULL),
  ('admin_retailer_verification','module',NULL),
  ('admin_retailer_photo_update','module',NULL),
  ('admin_retailer_territory_assignment','module',NULL),
  ('admin_van_sales','module',NULL),
  ('admin_van_list','module',NULL),
  ('admin_van_create','module',NULL),
  ('admin_van_edit','module',NULL),
  ('admin_van_driver_assignment','module',NULL),
  ('admin_van_stock_view','module',NULL),
  ('admin_van_opening_grn_edits','module',NULL),
  ('admin_security_access','module',NULL),
  ('admin_security_profiles','module',NULL),
  ('admin_profile_permissions','module',NULL),
  ('admin_user_specific_permissions','module',NULL),
  ('admin_feature_mgmt','module',NULL),
  ('admin_feature_flags','module',NULL),
  ('admin_feature_toggle','module',NULL),
  ('admin_gamification','module',NULL),
  ('admin_gamification_config','module',NULL),
  ('admin_badges_management','module',NULL),
  ('admin_rewards_management','module',NULL),
  ('admin_redemption_management','module',NULL),
  ('admin_retailer_loyalty','module',NULL),
  ('admin_loyalty_programs','module',NULL),
  ('admin_loyalty_points','module',NULL),
  ('admin_loyalty_redemptions','module',NULL),
  ('admin_company_profile','module',NULL),
  ('admin_company_details','module',NULL),
  ('admin_bank_information','module',NULL),
  ('admin_header_branding','module',NULL),
  ('admin_invoice_mgmt','module',NULL),
  ('admin_invoice_list','module',NULL),
  ('admin_invoice_create','module',NULL),
  ('admin_invoice_templates','module',NULL),
  ('admin_credit_mgmt','module',NULL),
  ('admin_credit_scoring_config','module',NULL),
  ('admin_credit_limits','module',NULL),
  ('admin_recycle_bin','module',NULL),
  ('admin_recycle_bin_settings','module',NULL),
  ('admin_permanent_deletion_logs','module',NULL),
  ('admin_restore_deleted_items','module',NULL),
  ('admin_distributor_portal','module',NULL),
  ('admin_portal_users','module',NULL),
  ('admin_portal_orders','module',NULL),
  ('admin_portal_inventory','module',NULL),
  ('admin_portal_claims','module',NULL),
  ('admin_portal_support','module',NULL),
  ('admin_portal_ideas','module',NULL),
  ('admin_target_vs_actual','module',NULL),
  ('admin_target_setting','module',NULL),
  ('admin_target_tracking','module',NULL),
  ('admin_hierarchy_targets','module',NULL),
  ('admin_hierarchy_target_setup','module',NULL),
  ('admin_target_cascade','module',NULL),
  ('admin_allocation_methods','module',NULL),
  ('admin_notification_rules','module',NULL),
  ('admin_notification_rules_list','module',NULL),
  ('admin_notification_rules_create','module',NULL),
  ('admin_notification_rules_edit','module',NULL),
  ('admin_pincode_master','module',NULL),
  ('admin_pincode_list','module',NULL),
  ('admin_pincode_import','module',NULL),
  ('admin_tax_master','module',NULL),
  ('admin_retailer_ext_db','module',NULL),
  ('admin_retailer_ext_search','module',NULL),
  ('admin_retailer_ext_export','module',NULL),
  ('admin_user_mgmt','module',NULL),
  ('admin_system_settings','module',NULL),
  ('tax_master','module',NULL),
  ('tax_master_list','module',NULL),
  ('tax_master_create','module',NULL),
  ('tax_master_edit','module',NULL),
  ('tax_master_delete','module',NULL),
  ('tax_component_manage','module',NULL),
  ('tax_product_mapping','module',NULL)
)
INSERT INTO public.profile_object_permissions
  (profile_id, object_name, permission_type, parent_module,
   can_read, can_create, can_edit, can_delete, can_view_all, can_modify_all)
SELECT sp.id, c.object_name, c.permission_type, c.parent_module,
       true, true, true, true, true, true
FROM public.security_profiles sp
CROSS JOIN catalog c
WHERE sp.is_system = true
ON CONFLICT (profile_id, object_name, permission_type) DO UPDATE
  SET can_read       = true,
      can_create     = true,
      can_edit       = true,
      can_delete     = true,
      can_view_all   = true,
      can_modify_all = true,
      parent_module  = COALESCE(EXCLUDED.parent_module, public.profile_object_permissions.parent_module);

-- Also ensure any other admin_* / non-admin permission keys that already exist for
-- other profiles are mirrored onto every system profile with full flags (safety net).
INSERT INTO public.profile_object_permissions
  (profile_id, object_name, permission_type, parent_module,
   can_read, can_create, can_edit, can_delete, can_view_all, can_modify_all)
SELECT sp.id, x.object_name, x.permission_type, MAX(x.parent_module),
       true, true, true, true, true, true
FROM public.security_profiles sp
CROSS JOIN public.profile_object_permissions x
WHERE sp.is_system = true
GROUP BY sp.id, x.object_name, x.permission_type
ON CONFLICT (profile_id, object_name, permission_type) DO UPDATE
  SET can_read = true, can_create = true, can_edit = true,
      can_delete = true, can_view_all = true, can_modify_all = true;

-- Backfill trigger: any future is_system=true profile creation auto-populates full perms.
CREATE OR REPLACE FUNCTION public.backfill_system_profile_permissions()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.is_system IS DISTINCT FROM true THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.profile_object_permissions
    (profile_id, object_name, permission_type, parent_module,
     can_read, can_create, can_edit, can_delete, can_view_all, can_modify_all)
  SELECT NEW.id, x.object_name, x.permission_type, MAX(x.parent_module),
         true, true, true, true, true, true
  FROM public.profile_object_permissions x
  GROUP BY x.object_name, x.permission_type
  ON CONFLICT (profile_id, object_name, permission_type) DO UPDATE
    SET can_read = true, can_create = true, can_edit = true,
        can_delete = true, can_view_all = true, can_modify_all = true;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_backfill_system_profile ON public.security_profiles;
CREATE TRIGGER trg_backfill_system_profile
AFTER INSERT ON public.security_profiles
FOR EACH ROW EXECUTE FUNCTION public.backfill_system_profile_permissions();